# List of devices you want to take the screenshots from
devices([
    "iPhone 8 Plus",
    "iPhone 11 Pro Max"
])

 languages([
  "en-US"
])

scheme("screenshots")
output_directory("./fastlane/screenshots")